# Cloudflare Workers configuration for josemianton.com
# Static site deployment to Workers

name = "josemianton-com"
compatibility_date = "2025-09-13"
compatibility_flags = ["nodejs_compat"]

# Static assets configuration - serves the entire static site
[assets]
directory = "dist"
not_found_handling = "single-page-application"