# Cloudflare Workers configuration for josemianton.com
# Hybrid deployment: Worker + Static Assets + R2

name = "josemianton-com"
main = "worker.js"
compatibility_date = "2025-09-13"
compatibility_flags = ["nodejs_compat"]

# Account ID is set via environment variable CF_ACCOUNT_ID for security
# account_id = set via CF_ACCOUNT_ID env var

# Static assets configuration - serves the Astro static site
[assets]
directory = "dist"
not_found_handling = "single-page-application"

# R2 bucket binding for portfolio images
[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "josemianton-com"

# Custom domain configuration
routes = [
  { pattern = "cdn.josemianton.com/*", custom_domain = true },
  { pattern = "josemianton.com", custom_domain = true },
  { pattern = "www.josemianton.com", custom_domain = true }
]
